### ISSUE TITLE
Unable to set schema

### ISSUE THREAD

**Issue by andresmgot** [Azure/monaco-kusto#187]
### Description

`languages.kusto.getKustoWorker()` never finishes, the promises it returns is stuck at "pending", no error is returned. My goal is to execute the following:

```
      languages.kusto
        .getKustoWorker()
        .then((kusto) => {
          const model = editor.getModel();
          return model && kusto(model.uri);
        })
        .then((worker) => {
          worker?.setSchema(schema, 'https://help.kusto.windows.net', 'Samples');
        });
```

I believe this stopped working at some point. This is not working with monaco-editor: 0.31.1 and @kusto/monaco-kusto: 4.1.8 but it worked with monaco-editor 0.21.2 & @kusto/monaco-kusto: 3.2.7.

I suspect something is wrong with the language import since I get this message in the browser console when using kusto:

```
kustoMode.js:16 Uncaught TypeError: n.getModeId is not a function
    at a (kustoMode.js:16:71379)
    at Array.forEach (<anonymous>)
    at new n (kustoMode.js:16:72566)
    at Object.t.setupMode (kustoMode.js:16:86018)
    at monaco.contribution.js:7:3890
    at Function.s._invokeFactory (loader.js:8:1626)
    at s.complete (loader.js:8:1821)
    at s._onModuleComplete (loader.js:9:991)
    at s._onModuleComplete (loader.js:9:1235)
    at s._resolve (loader.js:9:510)
```

Any idea how to get this working? This is preventing us from upgrading the editor.

Thanks in advance @lidermanrony 

 ### Steps to Reproduce

Hopefully the explanation above is enough but let me know if I can provide more information.

 [Steps or usage snippet reproducing the issue]

 1. [First Step]
 2. [Second Step]
 3. [and so on...]

 ```
 <snippet>
 ```

 **Expected behavior:** [What you expect to happen]

 **Actual behavior:** [What actually happens]

 **Reproduces how often:** [What percentage of the time does it reproduce?]

 ### System configuration

 monaco-kusto version: 4.1.8
 monaco-editor version: 0.31.1
 Browser:
 OS:

**Comment by andresmgot** [comment]
Just tried the new version 5.0.0 and it fixed the issue :) I am not sure if I was lucky. Thanks!
